inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2

Naming/FileName:
  Exclude:
    - 'bin/git-fastclone'
    - 'lib/git-fastclone.rb'

Metrics/ClassLength:
  Max: 10000

Metrics/LineLength:
  Max: 110

Metrics/MethodLength:
  Max: 2000

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
